### ISSUE TITLE
About resnet_v2 default image size

### ISSUE THREAD

**Issue by tuji-sjp** [dongyp13/Translation-Invariant-Attacks#11]
Hello, **resnet_v2.default_image_size** is 224 in your ‘nets ’. But **image_width** and **image_height** are 299 in the 'attack_iter.py'. I wonder where you did the conversion?

Please help me solve this puzzle. Thank you very much.

**Comment by dongyp13** [comment]
Hi, we did not make any change but followed the slim repo [https://github.com/tensorflow/models/tree/master/research/slim](https://github.com/tensorflow/models/tree/master/research/slim) to set the input size of resnet_v2 (see `Pre-trained Models` in README) .

**Comment by tuji-sjp** [comment]
Ok, thanks a lot!
