### ISSUE TITLE
Where can I get the ensemble model?

### ISSUE THREAD

**Issue by qilong-zhang** [dongyp13/Translation-Invariant-Attacks#7]
Hi Yinpeng,

How to get the ensemble models Inc-v3ens3, Inc-v3ens4, IncRes-v2ens?

**Comment by qilong-zhang** [comment]
Does Ens4AdvInceptionV3 means Inc-v3ens4?

**Comment by dongyp13** [comment]
Right. You can find these models at http://ml.cs.tsinghua.edu.cn/~yinpeng/nips17/nontargeted/models.zip.

**Comment by qilong-zhang** [comment]
@dongyp13 Thanks!
