### ISSUE TITLE
The result about TI-FGSM

### ISSUE THREAD

**Issue by qilong-zhang** [dongyp13/Translation-Invariant-Attacks#8]
Hi,
From the pictures you showed, We can see that TI-FGSM can achieve good results. In you paper, you said the step size is1.6. But if I set the number of iteration as 10, the result are not good enough. 
And I noticed that I this repo, you said the  number of iteration as 1, and when I set the number of iteration as 1, I can get the same result.
So the result from your pictures is done by 1 iteration?
Thank you!

**Comment by dongyp13** [comment]
Hi,

The step size equals to `epsilon / iterations`. For TI-FGSM, the number of iterations is 1, so the step size is 16. And for iterative methods, we set the number of iterations as 10 in our experiments, so the step size is 1.6. If you do not use momentum or data augmentation, using 10 iterations will lead to poor results. The reason can be found in "Boosting Adversarial Attacks with Momentum".

**Comment by qilong-zhang** [comment]
Thanks!
