### ISSUE TITLE
The result about TI-DIM

### ISSUE THREAD

**Issue by qilong-zhang** [dongyp13/Translation-Invariant-Attacks#9]
Hi Yinpeng,

Happy new year!  I run your code to test the result of TI-DIM, but my result is really bad! 
For TI-DIM, I use single model "InceptionV3" and I set num_iter=10, prob=0.7, kernel_legth=15, nsig=3, but my result is
```
sum_ens3_adv_v3 = 242
sum_ens4_adv_v3 = 267
sum_ensadv_Incres_v2 = 168
```
And I notice you also set momentum=1.0, Do you mean than DIM = DI-FGSM + MI-FGSM?
If I use momentum, the result is really close to yours and even a little better
```
sum_ens3_adv_v3 = 503
sum_ens4_adv_v3 = 521
sum_ensadv_Incres_v2 = 405
```
Could you help me?

**Comment by dongyp13** [comment]
Yes, you are right. I use momentum=1.0 for DIM.
